config/routes.rb
Rails.application.routes.draw do

  resources :recipies
  resources :users

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/recipy.rb
class Recipy < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/recipies_controller.rb
class RecipiesController < ApplicationController
  before_action :set_recipy, only: %i[ show edit update destroy ]

  # GET /recipies or /recipies.json
  def index
    @recipies = Recipy.all
  end

  # GET /recipies/1 or /recipies/1.json
  def show
  end

  # GET /recipies/new
  def new
    @recipy = Recipy.new
  end

  # GET /recipies/1/edit
  def edit
  end

  # POST /recipies or /recipies.json
  def create
    @recipy = Recipy.new(recipy_params)

    respond_to do |format|
      if @recipy.save
        format.html { redirect_to recipy_url(@recipy), notice: "Recipy was successfully created." }
        format.json { render :show, status: :created, location: @recipy }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @recipy.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /recipies/1 or /recipies/1.json
  def update
    respond_to do |format|
      if @recipy.update(recipy_params)
        format.html { redirect_to recipy_url(@recipy), notice: "Recipy was successfully updated." }
        format.json { render :show, status: :ok, location: @recipy }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @recipy.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /recipies/1 or /recipies/1.json
  def destroy
    @recipy.destroy

    respond_to do |format|
      format.html { redirect_to recipies_url, notice: "Recipy was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_recipy
      @recipy = Recipy.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def recipy_params
      params.fetch(:recipy, {})
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Team</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/recipies/_form.html.erb
<%= form_with(model: recipy) do |form| %>
  <% if recipy.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(recipy.errors.count, "error") %> prohibited this recipy from being saved:</h2>

      <ul>
        <% recipy.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/recipies/edit.html.erb
<h1>Editing Recipy</h1>

<%= render 'form', recipy: @recipy %>

<%= link_to 'Show', @recipy %> |
<%= link_to 'Back', recipies_path %>

app/views/recipies/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Recipies</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @recipies.each do |recipy| %>
      <tr>
        <td><%= link_to 'Show', recipy %></td>
        <td><%= link_to 'Edit', edit_recipy_path(recipy) %></td>
        <td><%= link_to 'Destroy', recipy, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Recipy', new_recipy_path %>

app/views/recipies/new.html.erb
<h1>New Recipy</h1>

<%= render 'form', recipy: @recipy %>

<%= link_to 'Back', recipies_path %>

app/views/recipies/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_recipy_path(@recipy) %> |
<%= link_to 'Back', recipies_path %>